CREATE DATABASE DETETIVE
GO

USE DETETIVE
GO

CREATE TABLE TB_SUSPEITO(

ID_SUSPEITO INT NOT NULL IDENTITY(1,1),
NM_SUSPEITO VARCHAR (200) NOT NULL

CONSTRAINT PK_TB_SUSPEITO_ID_SUSPEITO PRIMARY KEY(ID_SUSPEITO)
)
GO

INSERT INTO TB_SUSPEITO VALUES ('Esqueleto')
INSERT INTO TB_SUSPEITO VALUES ('Khan')
INSERT INTO TB_SUSPEITO VALUES ('Darth Vader')
INSERT INTO TB_SUSPEITO VALUES ('Sideshow Bob')
INSERT INTO TB_SUSPEITO VALUES ('Coringa')
INSERT INTO TB_SUSPEITO VALUES ('Duende Verde')
GO

CREATE TABLE TB_LOCAL (

ID_LOCAL INT NOT NULL IDENTITY(1,1),
NM_LOCAL VARCHAR (200) NOT NULL,

CONSTRAINT PK_TB_LOCAL_ID_LOCAL PRIMARY KEY(ID_LOCAL)
)
GO

INSERT INTO TB_LOCAL VALUES('Etérnia')
INSERT INTO TB_LOCAL VALUES('Vulcano')
INSERT INTO TB_LOCAL VALUES('Tatooine')
INSERT INTO TB_LOCAL VALUES('Springfield')
INSERT INTO TB_LOCAL VALUES('Gotham')
INSERT INTO TB_LOCAL VALUES('Nova York')
INSERT INTO TB_LOCAL VALUES('Sibéria')
INSERT INTO TB_LOCAL VALUES('Machu Picchu')
INSERT INTO TB_LOCAL VALUES('Show do Katinguele')
INSERT INTO TB_LOCAL VALUES('São Paulo')
GO

CREATE TABLE TB_ARMA (

ID_ARMA INT NOT NULL IDENTITY(1,1),
NM_ARMA VARCHAR (200) NOT NULL,

CONSTRAINT PK_TB_ARMA_ID_ARMA PRIMARY KEY(ID_ARMA)
)
GO

INSERT INTO TB_ARMA VALUES('Cajado Devastador')
INSERT INTO TB_ARMA VALUES('Phaser')
INSERT INTO TB_ARMA VALUES('Peixeira')
INSERT INTO TB_ARMA VALUES('Trezoitão')
INSERT INTO TB_ARMA VALUES('Sabre de Luz')
INSERT INTO TB_ARMA VALUES('Bomba')
GO

CREATE TABLE TB_ASSASSINATO(

ID_ASSASSINATO INT NOT NULL IDENTITY(1,1),
ID_SUSPEITO INT NOT NULL,
ID_LOCAL INT NOT NULL,
ID_ARMA INT NOT NULL,
DT_CADASTRO DATETIME NOT NULL CONSTRAINT DF_TB_ASSASSINATO_DT_CADASTRO DEFAULT (GETDATE()),

CONSTRAINT PK_TB_ASSASSINATO_ID_ASSASSINATO PRIMARY KEY(ID_ASSASSINATO),
CONSTRAINT FK_TB_ASSASSINATO_ID_SUSPEITO FOREIGN KEY (ID_SUSPEITO) REFERENCES TB_SUSPEITO,
CONSTRAINT FK_TB_ASSASSINATO_ID_LOCAL FOREIGN KEY (ID_LOCAL) REFERENCES TB_LOCAL,
CONSTRAINT FK_TB_ASSASSINATO_ID_ARMA FOREIGN KEY (ID_ARMA) REFERENCES TB_ARMA
)
GO